const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const screens=$$('.screen'), navBtns=$$('.bottom-nav button'), toast=$('#toast');
let catalog={violations:[]}, selectedStop=null, severityChoice='';

function show(name){screens.forEach(x=>x.classList.toggle('active',x.dataset.screen===name));navBtns.forEach(b=>b.classList.toggle('active',b.dataset.open===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='myStops')loadStops();}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.open))); $('#profileBtn').addEventListener('click',()=>show('profile'));
function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove('show'),2800)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
function device(){let id=localStorage.getItem('pb_mng_device_id'),token=localStorage.getItem('pb_mng_device_token');if(!id){id=crypto.randomUUID();localStorage.setItem('pb_mng_device_id',id)}if(!token){token=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('pb_mng_device_token',token)}return{id,token}}
function headers(extra={}){const d=device();return{'X-PB-Device':d.id,'X-PB-Token':d.token,...extra}}
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{...headers(),...(opts.headers||{})}});let data=null;const ct=r.headers.get('content-type')||'';if(ct.includes('json'))data=await r.json();else data=await r.text();if(!r.ok)throw new Error(data?.detail||data||`HTTP ${r.status}`);return data}

function profile(){return JSON.parse(localStorage.getItem('pb_mng_profile')||'{}')}
function applyProfile(){const p=profile();$('#profileName').value=p.name||'';$('#profileUnit').value=p.unit||'';$('#profilePass').value=p.pass||'';$('#workerLabel').textContent=p.name||'Заполните профиль';$('#profileBtn').textContent=(p.name||'ПБ').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
$('#saveProfile').addEventListener('click',()=>{const p={name:$('#profileName').value.trim(),unit:$('#profileUnit').value.trim(),pass:$('#profilePass').value.trim()};if(!p.name){say('Укажите ФИО');return}localStorage.setItem('pb_mng_profile',JSON.stringify(p));applyProfile();say('Данные сохранены');show('home')}); applyProfile();

function fillSelect(id,values,placeholder){const el=$(id);el.innerHTML=`<option value="">${placeholder}</option>`+(values||[]).map(v=>`<option>${escapeHtml(v)}</option>`).join('')}
async function loadCatalog(){try{catalog=await api('/api/pb-mng/catalog');fillSelect('#block',catalog.blocks,'Выберите блок');fillSelect('#structuralUnit',catalog.units,'Выберите подразделение');fillSelect('#field',catalog.fields,'Выберите месторождение');fillSelect('#workType',catalog.work_types,'Выберите вид работ');$('#contractorList').innerHTML=(catalog.contractors||[]).map(v=>`<option value="${escapeHtml(v)}"></option>`).join('');$('#violation').innerHTML='<option value="">Выберите нарушение</option>'+(catalog.violations||[]).map(v=>`<option value="${v.id}">${escapeHtml(v.number+'. '+v.text)}</option>`).join('');setConnection(true);restoreDraft();}catch(e){setConnection(false,e.message);$('#violation').innerHTML='<option value="">Нет связи с сервером</option>';}}
function setConnection(ok,msg=''){const c=$('#connectionCard');c.classList.toggle('offline',!ok);$('#connectionTitle').textContent=ok?'Сервер доступен':'Нет связи с сервером';$('#connectionText').textContent=ok?'Карточки передаются в реестр':(msg||'Черновик можно сохранить на устройстве')}

$('#violation').addEventListener('change',()=>{const rule=catalog.violations.find(x=>x.id===$('#violation').value);severityChoice='';const preview=$('#violationPreview'), box=$('#classification'), criteria=$('#criteriaBox');if(!rule){preview.classList.add('hidden');box.classList.add('hidden');criteria.classList.add('hidden');return}$('#barrierText').textContent=rule.barrier||'—';preview.classList.remove('hidden');const labels=catalog.severity_labels||{gross:'Грубое',significant:'Значительное',minor:'Незначительное'};if(rule.severities.length===1){severityChoice=rule.severities[0];$('#levelText').textContent=labels[severityChoice]||severityChoice;box.className='classification '+(severityChoice==='gross'?'gross':severityChoice==='minor'?'minor':'');criteria.classList.add('hidden');}else{box.classList.add('hidden');criteria.classList.remove('hidden');const crit=rule.criteria||{};$('#severityChoices').innerHTML=rule.severities.map(s=>`<label class="severity-option"><input type="radio" name="severity" value="${s}"><span><b>${escapeHtml(labels[s]||s)}</b><small>${escapeHtml(crit[s]||'Выберите при соответствии фактической ситуации')}</small></span></label>`).join('');$$('input[name="severity"]',$('#severityChoices')).forEach(r=>r.addEventListener('change',()=>{severityChoice=r.value;}));}});

function updateNow(){const d=new Date();$('#nowLabel').textContent=formatDate(d.toISOString())}updateNow();setInterval(updateNow,60000);
$('#photos').addEventListener('change',e=>{const files=[...e.target.files].slice(0,5);$('#photoList').innerHTML='';files.forEach(f=>{const img=document.createElement('img');img.src=URL.createObjectURL(f);$('#photoList').appendChild(img)});$('#photoCount').textContent=files.length+'/5'});

function draftPayload(){return{block:$('#block').value,structural_unit:$('#structuralUnit').value,field:$('#field').value,location:$('#location').value,contractor:$('#contractor').value,subcontractor:$('#subcontractor').value,work_type:$('#workType').value,permit_number:$('#permitNumber').value,violation_id:$('#violation').value,severity:severityChoice,severity_context:$('#severityContext').value,description:$('#description').value,responsible:{fio:$('#responsibleFio').value,position:$('#responsiblePosition').value,pass:$('#responsiblePass').value}}}
$('#saveDraft').addEventListener('click',()=>{localStorage.setItem('pb_mng_draft',JSON.stringify(draftPayload()));say('Черновик сохранён на устройстве')});
function restoreDraft(){const d=JSON.parse(localStorage.getItem('pb_mng_draft')||'null');if(!d)return;const map={block:'#block',structural_unit:'#structuralUnit',field:'#field',location:'#location',contractor:'#contractor',subcontractor:'#subcontractor',work_type:'#workType',permit_number:'#permitNumber',violation_id:'#violation',description:'#description'};Object.entries(map).forEach(([k,s])=>{if(d[k]!=null)$(s).value=d[k]});if(d.responsible){$('#responsibleFio').value=d.responsible.fio||'';$('#responsiblePosition').value=d.responsible.position||'';$('#responsiblePass').value=d.responsible.pass||''}$('#violation').dispatchEvent(new Event('change'));if(d.severity){severityChoice=d.severity;setTimeout(()=>{const r=$(`input[name="severity"][value="${d.severity}"]`);if(r)r.checked=true},0)}$('#severityContext').value=d.severity_context||'';}

$('#stopForm').addEventListener('submit',async e=>{e.preventDefault();const p=profile();if(!p.name){say('Сначала заполните профиль');show('profile');return}const files=[...$('#photos').files].slice(0,5);if(!files.length){say('Добавьте фото нарушения');return}const rule=catalog.violations.find(x=>x.id===$('#violation').value);if(!rule){say('Выберите нарушение');return}if(rule.severities.length>1&&!severityChoice){say('Уточните категорию нарушения');return}const d=device();const payload={...draftPayload(),device_id:d.id,device_token:d.token,initiator:p,occurred_at:new Date().toISOString()};const fd=new FormData();fd.append('payload_json',JSON.stringify(payload));files.forEach(f=>fd.append('photos',f));const btn=$('#submitStop');btn.disabled=true;btn.textContent='Отправляем…';try{const data=await api('/api/pb-mng/stops',{method:'POST',body:fd});localStorage.removeItem('pb_mng_draft');e.target.reset();$('#photoList').innerHTML='';$('#photoCount').textContent='0/5';severityChoice='';say(`Остановка ${data.id} отправлена координатору`);await loadStops();setTimeout(()=>show('myStops'),500)}catch(err){say(err.message);localStorage.setItem('pb_mng_draft',JSON.stringify(draftPayload()));}finally{btn.disabled=false;btn.textContent='Отправить на верификацию'}});

function statusClass(s){if(s==='closed')return'green';if(['pending_verification','resolution_submitted'].includes(s))return'blue';if(s==='rejected')return'red';return'amber'}
async function loadStops(){try{const data=await api('/api/pb-mng/my-stops');const items=data.items||[];$('#activeCount').textContent=items.filter(x=>!['closed','rejected'].includes(x.status)).length;$('#actionCount').textContent=items.filter(x=>['returned_for_revision','awaiting_resolution','resolution_revision','awaiting_pkm'].includes(x.status)).length;$('#closedCount').textContent=items.filter(x=>x.status==='closed').length;const need=items.find(x=>['returned_for_revision','awaiting_resolution','resolution_revision'].includes(x.status));if(need){$('#attentionCard').classList.remove('hidden');$('#attentionTitle').textContent=need.status_label;$('#attentionText').textContent=`${need.id} · ${need.violation.text}`;}else $('#attentionCard').classList.add('hidden');$('#stopsList').innerHTML=items.length?items.map(x=>`<button class="stop-list-item" data-stop="${x.id}"><span class="status ${statusClass(x.status)}">${escapeHtml(x.status_label)}</span><h3>${x.id}</h3><p>${escapeHtml(x.violation.text)}</p><footer><span>${escapeHtml(x.location||x.field||'')}</span><b>${formatDate(x.created_at)}</b></footer></button>`).join(''):'<div class="empty-card">У вас пока нет остановок.</div>';$$('[data-stop]').forEach(b=>b.addEventListener('click',()=>openStop(b.dataset.stop)));setConnection(true);}catch(e){$('#stopsList').innerHTML=`<div class="empty-card">${escapeHtml(e.message)}</div>`;setConnection(false,e.message)}}
$('#refreshStops').addEventListener('click',loadStops);

async function openStop(id){try{selectedStop=await api('/api/pb-mng/stops/'+encodeURIComponent(id));renderDetail();show('stopDetail')}catch(e){say(e.message)}}
function renderDetail(){const x=selectedStop;if(!x)return;$('#detailId').textContent=x.id;$('#detailStatus').textContent=x.status_label;$('#detailBody').innerHTML=`<div class="form-card stop-detail"><div class="detail-grid"><span>Категория</span><b>${escapeHtml(x.severity_label)}</b><span>Подрядчик</span><b>${escapeHtml(x.contractor||'—')}</b><span>Объект</span><b>${escapeHtml([x.field,x.location].filter(Boolean).join(' · ')||'—')}</b><span>Вид работ</span><b>${escapeHtml(x.work_type||'—')}</b><span>Ответственный</span><b>${escapeHtml(x.responsible.fio||'—')} ${escapeHtml(x.responsible.pass||'')}</b></div><h3>Нарушение</h3><p>${escapeHtml(x.violation.text)}</p><h3>Описание</h3><p>${escapeHtml(x.description||'—')}</p>${x.verification_note?`<div class="note-box"><b>Комментарий координатора</b><p>${escapeHtml(x.verification_note)}</p></div>`:''}${x.measures?.length?`<h3>Меры</h3><ul>${x.measures.map(m=>`<li>${escapeHtml(m)}</li>`).join('')}</ul>`:''}${x.restrictions?.length?`<div class="block-banner">Пропуск заблокирован до выполнения условий возобновления${x.restrictions[0].ends_at?' / '+formatDate(x.restrictions[0].ends_at):''}</div>`:''}</div>`;$('#resolutionBox').classList.toggle('hidden',!['awaiting_resolution','resolution_revision'].includes(x.status));$('#pkmBox').classList.toggle('hidden',!(x.status==='awaiting_pkm'&&['required','revision'].includes(x.pkm_status)));$('#pkmText').value=x.pkm_text||'';$('#revisionBox').classList.toggle('hidden',x.status!=='returned_for_revision');$('#revisionText').textContent=x.verification_note||'';$('#revisionDescription').value=x.description||'';}
$('#afterPhoto').addEventListener('change',e=>{$('#afterPhotoText').textContent=e.target.files.length?`Добавлено: ${e.target.files.length}`:'Обязательно'});
$('#submitResolution').addEventListener('click',async()=>{if(!selectedStop)return;const files=[...$('#afterPhoto').files].slice(0,5);if(!files.length){say('Добавьте фото после устранения');return}const fd=new FormData();fd.append('comment',$('#resolutionComment').value);files.forEach(f=>fd.append('photos',f));try{selectedStop=await api(`/api/pb-mng/stops/${selectedStop.id}/resolution`,{method:'POST',body:fd});say('Подтверждение отправлено координатору');renderDetail();loadStops()}catch(e){say(e.message)}});
$('#resubmitStop').addEventListener('click',async()=>{if(!selectedStop)return;const fd=new FormData();fd.append('payload_json',JSON.stringify({description:$('#revisionDescription').value,location:selectedStop.location}));[...$('#revisionPhotos').files].slice(0,5).forEach(f=>fd.append('photos',f));try{selectedStop=await api(`/api/pb-mng/stops/${selectedStop.id}/resubmit`,{method:'POST',body:fd});say('Карточка повторно отправлена');renderDetail();loadStops()}catch(e){say(e.message)}});

loadCatalog(); loadStops();

$('#submitPkm').addEventListener('click',async()=>{if(!selectedStop)return;const fd=new FormData();fd.append('text',$('#pkmText').value);try{selectedStop=await api(`/api/pb-mng/stops/${selectedStop.id}/pkm`,{method:'POST',body:fd});say('ПКМ отправлен координатору');renderDetail();loadStops()}catch(e){say(e.message)}});