const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const screens=$$('.screen'), navBtns=$$('.bottom-nav button'), toast=$('#toast');
let catalog={}, selectedStop=null;

function show(name){screens.forEach(x=>x.classList.toggle('active',x.dataset.screen===name));navBtns.forEach(b=>b.classList.toggle('active',b.dataset.open===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='myStops')loadStops();}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.open))); $('#profileBtn').addEventListener('click',()=>show('profile'));
function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove('show'),2800)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
function device(){let id=localStorage.getItem('pb_mng_device_id'),token=localStorage.getItem('pb_mng_device_token');if(!id){id=crypto.randomUUID();localStorage.setItem('pb_mng_device_id',id)}if(!token){token=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('pb_mng_device_token',token)}return{id,token}}
function headers(extra={}){const d=device();return{'X-PB-Device':d.id,'X-PB-Token':d.token,...extra}}
async function api(url,opts={}){const useDeviceHeaders=opts.deviceHeaders!==false;const fetchOpts={...opts};delete fetchOpts.deviceHeaders;const r=await fetch(url,{...fetchOpts,cache:fetchOpts.cache||'no-store',headers:{...(useDeviceHeaders?headers():{}),...(fetchOpts.headers||{})}});let data=null;const ct=r.headers.get('content-type')||'';if(ct.includes('json'))data=await r.json();else data=await r.text();if(!r.ok)throw new Error(data?.detail||data||`HTTP ${r.status}`);return data}

function profile(){return JSON.parse(localStorage.getItem('pb_mng_profile')||'{}')}
function applyProfile(){const p=profile();$('#profileName').value=p.name||'';$('#profileUnit').value=p.unit||'';$('#profilePass').value=p.pass||'';$('#workerLabel').textContent=p.name||'Заполните профиль';$('#profileBtn').textContent=(p.name||'ПБ').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
$('#saveProfile').addEventListener('click',()=>{const p={name:$('#profileName').value.trim(),unit:$('#profileUnit').value.trim(),pass:$('#profilePass').value.trim()};if(!p.name){say('Укажите ФИО');return}localStorage.setItem('pb_mng_profile',JSON.stringify(p));applyProfile();say('Данные сохранены');show('home')}); applyProfile();

function fillSelect(id,values,placeholder){const el=$(id);const keep=el.value;el.innerHTML=`<option value="">${placeholder}</option>`+(values||[]).map(v=>`<option>${escapeHtml(v)}</option>`).join('');if(keep&&[...el.options].some(o=>o.value===keep))el.value=keep}
const CATALOG_CACHE_KEY='pb_mng_catalog_v1';
let catalogRetryTimer=null;
function applyCatalog(data,{restore=true}={}){if(!data)throw new Error('Пустые справочники');catalog=data;fillSelect('#block',catalog.blocks,'Выберите блок');fillSelect('#structuralUnit',catalog.units,'Выберите подразделение');fillSelect('#field',catalog.fields,'Выберите месторождение');fillSelect('#workType',catalog.work_types,'Выберите вид работ');$('#contractorList').innerHTML=(catalog.contractors||[]).map(v=>`<option value="${escapeHtml(v)}"></option>`).join('');if(restore)restoreDraft();}
function readCachedCatalog(){try{return JSON.parse(localStorage.getItem(CATALOG_CACHE_KEY)||'null')}catch{return null}}
function scheduleCatalogRetry(){clearTimeout(catalogRetryTimer);catalogRetryTimer=setTimeout(()=>loadCatalog({silent:true,restore:false}),8000)}
async function loadCatalog({silent=false,restore=true}={}){const cached=readCachedCatalog();if(cached&&(!catalog.blocks||!catalog.blocks.length)){try{applyCatalog(cached,{restore});setConnection(false,'Справочники доступны. Восстанавливаю соединение с сервером…')}catch{}}let lastError=null;for(let attempt=1;attempt<=3;attempt++){try{const fresh=await api('/api/pb-mng/catalog',{deviceHeaders:false,cache:'no-store'});applyCatalog(fresh,{restore:restore&&attempt===1});localStorage.setItem(CATALOG_CACHE_KEY,JSON.stringify(fresh));setConnection(true);clearTimeout(catalogRetryTimer);return true}catch(e){lastError=e;if(attempt<3)await new Promise(r=>setTimeout(r,700*attempt));}}if(cached){setConnection(false,'Связь временно недоступна. Справочники загружены с устройства.');scheduleCatalogRetry();if(!silent)say('Связь с сервером восстанавливается');return false}setConnection(false,lastError?.message||'Сервер временно недоступен');scheduleCatalogRetry();if(!silent)say('Не удалось получить справочники. Повторяю подключение…');return false}
function setConnection(ok,msg=''){const c=$('#connectionCard');c.classList.toggle('offline',!ok);$('#connectionTitle').textContent=ok?'Сервер доступен':'Связь восстанавливается';$('#connectionText').textContent=ok?'Карточки передаются в реестр':(msg||'Черновик можно сохранить на устройстве')}

function updateNow(){const d=new Date();$('#nowLabel').textContent=formatDate(d.toISOString())}updateNow();setInterval(updateNow,60000);
$('#photos').addEventListener('change',e=>{const files=[...e.target.files].slice(0,5);$('#photoList').innerHTML='';files.forEach(f=>{const img=document.createElement('img');img.src=URL.createObjectURL(f);$('#photoList').appendChild(img)});$('#photoCount').textContent=files.length+'/5'});

function draftPayload(){return{block:$('#block').value,structural_unit:$('#structuralUnit').value,field:$('#field').value,location:$('#location').value,contractor:$('#contractor').value,subcontractor:$('#subcontractor').value,work_type:$('#workType').value,permit_number:$('#permitNumber').value,description:$('#description').value,responsible:{fio:$('#responsibleFio').value,position:$('#responsiblePosition').value,pass:$('#responsiblePass').value}}}
$('#saveDraft').addEventListener('click',()=>{localStorage.setItem('pb_mng_draft',JSON.stringify(draftPayload()));say('Черновик сохранён на устройстве')});
function restoreDraft(){const d=JSON.parse(localStorage.getItem('pb_mng_draft')||'null');if(!d)return;const map={block:'#block',structural_unit:'#structuralUnit',field:'#field',location:'#location',contractor:'#contractor',subcontractor:'#subcontractor',work_type:'#workType',permit_number:'#permitNumber',description:'#description'};Object.entries(map).forEach(([k,s])=>{if(d[k]!=null&&$(s))$(s).value=d[k]});if(d.responsible){$('#responsibleFio').value=d.responsible.fio||'';$('#responsiblePosition').value=d.responsible.position||'';$('#responsiblePass').value=d.responsible.pass||'';}}


$('#stopForm').addEventListener('submit',async e=>{e.preventDefault();const p=profile();if(!p.name){say('Сначала заполните профиль');show('profile');return}const files=[...$('#photos').files].slice(0,5);if(!files.length){say('Добавьте фото нарушения');return}const d=device();const payload={...draftPayload(),device_id:d.id,device_token:d.token,initiator:p,occurred_at:new Date().toISOString()};const fd=new FormData();fd.append('payload_json',JSON.stringify(payload));files.forEach(f=>fd.append('photos',f));const btn=$('#submitStop');btn.disabled=true;btn.textContent='Отправляем…';try{const data=await api('/api/pb-mng/stops',{method:'POST',body:fd});localStorage.removeItem('pb_mng_draft');e.target.reset();$('#photoList').innerHTML='';$('#photoCount').textContent='0/5';say(`Остановка ${data.id} отправлена координатору`);await loadStops();setTimeout(()=>show('myStops'),500)}catch(err){say(err.message);localStorage.setItem('pb_mng_draft',JSON.stringify(draftPayload()));}finally{btn.disabled=false;btn.textContent='Отправить на верификацию'}});


function statusClass(s){if(s==='closed')return'green';if(['pending_verification','resolution_submitted'].includes(s))return'blue';if(s==='rejected')return'red';return'amber'}
async function loadStops(){try{const data=await api('/api/pb-mng/my-stops');const items=data.items||[];$('#activeCount').textContent=items.filter(x=>!['closed','rejected'].includes(x.status)).length;$('#actionCount').textContent=items.filter(x=>['returned_for_revision','awaiting_resolution','resolution_revision','awaiting_pkm'].includes(x.status)).length;$('#closedCount').textContent=items.filter(x=>x.status==='closed').length;const need=items.find(x=>['returned_for_revision','awaiting_resolution','resolution_revision'].includes(x.status));if(need){$('#attentionCard').classList.remove('hidden');$('#attentionTitle').textContent=need.status_label;$('#attentionText').textContent=`${need.id} · ${need.violation.text||need.description||'Остановка работ'}`;}else $('#attentionCard').classList.add('hidden');$('#stopsList').innerHTML=items.length?items.map(x=>`<button class="stop-list-item" data-stop="${x.id}"><span class="status ${statusClass(x.status)}">${escapeHtml(x.status_label)}</span><h3>${x.id}</h3><p>${escapeHtml(x.violation.text||x.description||'Ожидается классификация координатором')}</p><footer><span>${escapeHtml(x.location||x.field||'')}</span><b>${formatDate(x.created_at)}</b></footer></button>`).join(''):'<div class="empty-card">У вас пока нет остановок.</div>';$$('[data-stop]').forEach(b=>b.addEventListener('click',()=>openStop(b.dataset.stop)));setConnection(true);}catch(e){$('#stopsList').innerHTML=`<div class="empty-card">${escapeHtml(e.message)}</div>`;setConnection(false,e.message)}}
$('#refreshStops').addEventListener('click',loadStops);

async function openStop(id){try{selectedStop=await api('/api/pb-mng/stops/'+encodeURIComponent(id));renderDetail();show('stopDetail')}catch(e){say(e.message)}}
function renderDetail(){const x=selectedStop;if(!x)return;$('#detailId').textContent=x.id;$('#detailStatus').textContent=x.status_label;const classified=!!x.violation?.id;$('#detailBody').innerHTML=`<div class="form-card stop-detail"><div class="detail-grid"><span>Классификация</span><b>${classified?escapeHtml(x.severity_label):'Ожидается координатор'}</b><span>Подрядчик</span><b>${escapeHtml(x.contractor||'—')}</b><span>Объект</span><b>${escapeHtml([x.field,x.location].filter(Boolean).join(' · ')||'—')}</b><span>Вид работ</span><b>${escapeHtml(x.work_type||'—')}</b><span>Ответственный</span><b>${escapeHtml(x.responsible.fio||'—')} ${escapeHtml(x.responsible.pass||'')}</b></div>${classified?`<h3>Классификация координатора</h3><p>${escapeHtml(x.violation.text)}</p>`:''}<h3>Описание обстоятельств</h3><p>${escapeHtml(x.description||'—')}</p>${x.verification_note?`<div class="note-box"><b>Комментарий координатора</b><p>${escapeHtml(x.verification_note)}</p></div>`:''}${x.measures?.length?`<h3>Меры</h3><ul>${x.measures.map(m=>`<li>${escapeHtml(m)}</li>`).join('')}</ul>`:''}${x.restrictions?.length?`<div class="block-banner">Пропуск заблокирован до выполнения условий возобновления${x.restrictions[0].ends_at?' / '+formatDate(x.restrictions[0].ends_at):''}</div>`:''}</div>`;$('#resolutionBox').classList.toggle('hidden',!['awaiting_resolution','resolution_revision'].includes(x.status));$('#pkmBox').classList.toggle('hidden',!(x.status==='awaiting_pkm'&&['required','revision'].includes(x.pkm_status)));$('#pkmText').value=x.pkm_text||'';$('#revisionBox').classList.toggle('hidden',x.status!=='returned_for_revision');$('#revisionText').textContent=x.verification_note||'';$('#revisionDescription').value=x.description||'';}

$('#afterPhoto').addEventListener('change',e=>{$('#afterPhotoText').textContent=e.target.files.length?`Добавлено: ${e.target.files.length}`:'Обязательно'});
$('#submitResolution').addEventListener('click',async()=>{if(!selectedStop)return;const files=[...$('#afterPhoto').files].slice(0,5);if(!files.length){say('Добавьте фото после устранения');return}const fd=new FormData();fd.append('comment',$('#resolutionComment').value);files.forEach(f=>fd.append('photos',f));try{selectedStop=await api(`/api/pb-mng/stops/${selectedStop.id}/resolution`,{method:'POST',body:fd});say('Подтверждение отправлено координатору');renderDetail();loadStops()}catch(e){say(e.message)}});
$('#resubmitStop').addEventListener('click',async()=>{if(!selectedStop)return;const fd=new FormData();fd.append('payload_json',JSON.stringify({description:$('#revisionDescription').value,location:selectedStop.location}));[...$('#revisionPhotos').files].slice(0,5).forEach(f=>fd.append('photos',f));try{selectedStop=await api(`/api/pb-mng/stops/${selectedStop.id}/resubmit`,{method:'POST',body:fd});say('Карточка повторно отправлена');renderDetail();loadStops()}catch(e){say(e.message)}});

loadCatalog(); loadStops();
window.addEventListener('online',()=>{loadCatalog({silent:true,restore:false});if(document.querySelector('[data-screen="myStops"].active'))loadStops();});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&navigator.onLine)loadCatalog({silent:true,restore:false});});

$('#submitPkm').addEventListener('click',async()=>{if(!selectedStop)return;const fd=new FormData();fd.append('text',$('#pkmText').value);try{selectedStop=await api(`/api/pb-mng/stops/${selectedStop.id}/pkm`,{method:'POST',body:fd});say('ПКМ отправлен координатору');renderDetail();loadStops()}catch(e){say(e.message)}});